[package]
name = "glib"
version = "0.1.0"
authors = ["zduny"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.28.0"
include_dir = "0.6.0"
regex = "1.3.6"
lazy_static = "1.4.0"
linked_hash_set = "0.1.3"
